### ISSUE TITLE
TypeError: Cannot read property 'insertBefore' of null

### ISSUE THREAD

**Issue by bastienJS** [angular-ui/ui-router#1275]
I have already found 2 other issues on this repository dealing with the same error message, but their solution did not help me.

I also does not seem to matter which angularJS version I use.

I am surprised that I can not reproduce this error on a plunker because it does not happen on plunker when I visit this url also my code seems locally to be the same. (I have just realized I can download the plunker and I try to run it tomorrow and let you guys know what happens...)

I am confused.

right when I enter #/projects/create in my url and activate that state the ui is fine everything loaded, but in my console I see this error:

Thats the plunker which does not show the error...:

http://plnkr.co/edit/pjkeLkbRHZ3UxOLDmLJd?p=preview

TypeError: Cannot read property 'insertBefore' of null
    at http://localhost:9000/bower_components/angularjs/angular.js:3108:13
    at forEach (http://localhost:9000/bower_components/angularjs/angular.js:328:18)
    at forEach.after (http://localhost:9000/bower_components/angularjs/angular.js:3107:5)
    at Object.JQLite.(anonymous function) [as after](http://localhost:9000/bower_components/angularjs/angular.js:3196:17)
    at Object.$AnimateProvider.$get.enter (http://localhost:9000/bower_components/angularjs/angular.js:4339:21)
    at Object.enter (http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.js:2667:57)
    at http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.js:2734:22
    at publicLinkFn (http://localhost:9000/bower_components/angularjs/angular.js:6134:29)
    at updateView (http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.js:2733:23)
    at http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.js:2697:11 angular.js:10318

**Comment by mathpere** [comment]
Hi,

I met the exact same bug explained here (w/ AngularJS 1.3.14 and ui-router 0.2.13)

I have to include jQuery to avoid this null pointer. I have not yet been able to figure out the cause.
