### ISSUE TITLE
Regression: ui-sref-active with nested states broken in 0.2.11 but not 0.2.10

### ISSUE THREAD

**Issue by kz26** [angular-ui/ui-router#1314]
Loading a template for a parent state throws the following error in 0.2.11 but not 0.2.10 due to `ui-sref-active`. This error seems to be non-fatal as everything still seems to work. Changing to `ui-sref-active-eq` fixes the error.

**Chrome console traceback:**

```
TypeError: Cannot read property 'name' of undefined
    at isMatch (http://angular-ui.github.io/ui-router/release/angular-ui-router.js:3606:39)
    at update (http://angular-ui.github.io/ui-router/release/angular-ui-router.js:3595:13)
    at Scope.$broadcast (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular.js:12952:28)
    at $state.transition.resolved.then.$state.transition (http://angular-ui.github.io/ui-router/release/angular-ui-router.js:2662:22)
    at wrappedCallback (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular.js:11561:81)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular.js:11647:26
    at Scope.$eval (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular.js:12673:28)
    at Scope.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular.js:12485:31)
    at Scope.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular.js:12777:24)
    at done (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular.js:8371:45) angular.js:10061
```

**State definition:**

```
$stateProvider
    .state 'myProfile', {
        url: '/myProfile'
        controller: 'MyProfileCtrl'
        templateUrl: 'index.html'
        abstract: true
    }
    .state 'myProfile.basicInfo', {
        url: '/basicInfo'
        templateUrl: 'basicInfo.html'
    }
```

**index.html**:

```
<ul>
    <li ui-sref-active="active"><a ui-sref="myProfile.basicInfo">Basic Info</a></li>
    <li ui-sref-active="active"><a ui-sref="myProfile.aboutMe">About Me</a></li>
</ul>
```

**Comment by SISSIYAM** [comment]
ui-sref-active-eq workd for me,thanks
