### ISSUE TITLE
Can't read 'insertbefore' of null if you have an active ng-if going to child state

### ISSUE THREAD

**Issue by epelc** [angular-ui/ui-router#1633]
Hello, this is a little complicated but I finally found out how to reproduce this issue.

If you have a parent state with an active `ng-if` inside of a `ui-view` and you navigate to a child state you recieve the following error.

Note I'm pretty sure you get something along the lines of `Parent is undefined` in firefox but this is what you get in the latest chrome
```
TypeError: Cannot read property 'insertBefore' of null
    at forEach.after (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:3152:13)
    at Object.JQLite.(anonymous function) [as after] (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:3236:17)
    at Object.enter (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:4655:23)
    at Object.enter (http://dev.advantagelumber.net/app/bundle.js:15066:22)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:23425:26
    at publicLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:6940:29)
    at boundTranscludeFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:7080:16)
    at controllersBoundTransclude (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:7733:18)
    at Object.ngIfWatchAction (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:23416:15)
    at Object.constantListener [as fn] (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:12784:20)
```

Example markup:
```
Parent html
<div ui-view>
    The ng-if must be true
    <div ng-if="1==1">
        some content
    </div>
</div>

Child html(can be anything)
<span>test</span>
```

Example state definitions
```
.state('parentState', {
        url: '/parent',
        templateUrl: '/parent.html'
    })
    .state('parentState.someChild', {
        url: '/child',
        templateUrl: '/child.html'
    })
```

You only get the error if `ng-if` is true before you go to the child state. Also this is only while using `ng-if` if you use `ng-show` you are fine. I'll make a plunkr if this isn't enough info let me know

**Comment by nateabele** [comment]
Plunkr?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
