### ISSUE TITLE
Error: has no method 'toLowerCase' creating route with only numbers.

### ISSUE THREAD

**Issue by cespon** [angular-ui/ui-router#1889]
To execute `yo angular-ui-router:route 404` returns:

```
TypeError: Object 404 has no method 'toLowerCase'
    at new Generator (/usr/local/lib/node_modules/generator-angular-ui-router/controller/index.js:11:30)
    at Environment.instantiate (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:281:10)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:258:15)
    at Generator.invoke (/usr/local/lib/node_modules/generator-angular-ui-router/node_modules/yeoman-generator/lib/actions/invoke.js:18:28)
    at /usr/local/lib/node_modules/generator-angular-ui-router/node_modules/yeoman-generator/lib/base.js:325:12
    at /usr/local/lib/node_modules/generator-angular-ui-router/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /usr/local/lib/node_modules/generator-angular-ui-router/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
    at iterate (/usr/local/lib/node_modules/generator-angular-ui-router/node_modules/yeoman-generator/node_modules/async/lib/async.js:134:13)
    at async.eachSeries (/usr/local/lib/node_modules/generator-angular-ui-router/node_modules/yeoman-generator/node_modules/async/lib/async.js:150:9)
    at _asyncMap (/usr/local/lib/node_modules/generator-angular-ui-router/node_modules/yeoman-generator/node_modules/async/lib/async.js:226:9)
```

No problems if I execute `yo angular-ui-router:route not-found-404`.

**Comment by nateabele** [comment]
No part of this stack trace contains a call to UI-Router, and we don't maintain any of Yeoman's UI-Router generators. Please report this issue to Yeoman. Thanks.
