### ISSUE TITLE
UI-Router and Content-Security-Policy

### ISSUE THREAD

**Issue by Zenuka** [angular-ui/ui-router#2251]
For the ui-router to work I need to enable 'unsafe-eval' for the script-src directive in the Content-Security-Policy (http://content-security-policy.com/). Is there a way for the ui-router to work without using eval(...)?

    EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
        at eval (native)
        at https://localhost:3000/Libs/jquery/dist/jquery.js:339:22
        at Function.jQuery.extend.globalEval (https://localhost:3000/Libs/jquery/dist/jquery.js:340:7)
        at jQuery.fn.extend.domManip (https://localhost:3000/Libs/jquery/dist/jquery.js:5985:16)
        at jQuery.fn.extend.append (https://localhost:3000/Libs/jquery/dist/jquery.js:5758:15)
        at null.<anonymous> (https://localhost:3000/Libs/jquery/dist/jquery.js:5884:18)
        at jQuery.access (https://localhost:3000/Libs/jquery/dist/jquery.js:4157:8)
        at jQuery.fn.extend.html (https://localhost:3000/Libs/jquery/dist/jquery.js:5848:10)
        at removePatch [as html] (https://localhost:3000/Libs/angular/angular.js:2292:25)
        at $interpolate.compile (https://localhost:3000/Libs/angular-ui-router/release/angular-ui-router.js:4011:18) <div class="content ng-scope" ui-view="">

I'm using ui-router version 0.2.15 and angular 1.2.28 (need IE8 support) and I have the ng-csp directive on the html element.

**Comment by nateabele** [comment]
I'm pretty sure this is not a UI Router-specific issue. See https://docs.angularjs.org/api/ng/directive/ngCsp

**Comment by Zenuka** [comment]
You are right, you can close this issue. Thanks!

**Comment by Zenuka** [comment]
The problem was that one template had some javascript on it. Removing that solved the issue.
