### ISSUE TITLE
Maximum call stack size exceeded with $stateChangeStart

### ISSUE THREAD

**Issue by seesoe** [angular-ui/ui-router#2286]
im using angular 1.4.7 and ui routes 0.2.15, i was getting the digest loop when i try to change state within `$stateChangeStart`

i changed the otherwise function in my config to the following and it get rid of the loop.
```js
    $urlRouterProvider.otherwise( function($injector, $location) {
        var $state = $injector.get('$state');
        $state.go('signin');
    });
```
However I am still getting 2 more errors on page loads and weird navigation issue. Here is my on state change code.

```js
    $rootScope.$on('$stateChangeStart', function (event, toState, toParams, fromState, fromParams) {
        var userInfo = $cookieStore.get('UserData');
  
        if (!userInfo) {
            if (toState.name !== 'signin') {
                $state.go('signin');
                event.preventDefault();
                return;
            }
        } else {
            $state.go("home");
            event.preventDefault();
            return;
        }
    });
```

and my routes
```js
    $stateProvider
    .state('signin', {
        url: '/signin',
        templateUrl: 'templates/signin.html',
        controller: 'signinController'
    })
    .state('home', {
        url: '/home',
        templateUrl: 'templates/home.html'
    })
    .state('settings', {
        url: '/settings',
        templateUrl: 'templates/settings.html',
    })
    .state('register', {
        url: '/register',
        templateUrl: 'templates/register.html',
    })
    ;
```

are the following 2 errors route setup issues?

```
angular.js:12477 Error: Maximum call stack size exceeded
<error>
    at formatError (http://192.168.1.126:8100/lib/angular/angular.js:12449:16)
    at http://192.168.1.126:8100/lib/angular/angular.js:12475:23
    at forEach (http://192.168.1.126:8100/lib/angular/angular.js:336:20)
    at Object.error (http://192.168.1.126:8100/lib/angular/angular.js:12474:11)
    at ident.$get (http://192.168.1.126:8100/lib/angular/angular.js:9246:18)
    at Scope.parent.$get.Scope.$broadcast (http://192.168.1.126:8100/lib/angular/angular.js:16313:15)
    at Object.y.transitionTo (http://192.168.1.126:8100/lib/angular-ui-router/angular-ui-router-0.2.15.js:7:17776)
    at Object.y.go (http://192.168.1.126:8100/lib/angular-ui-router/angular-ui-router-0.2.15.js:7:16391)
    at http://192.168.1.126:8100/js/app.js:110:20
    at Scope.parent.$get.Scope.$broadcast (http://192.168.1.126:8100/lib/angular/angular.js:16311:28)(anonymous function) @ angular.js:12477ident.$get @ angular.js:9246parent.$get.Scope.$broadcast @ angular.js:16313y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7y.go @ angular-ui-router-0.2.15.js:7(anonymous function) @ app.js:110parent.$get.Scope.$broadcast @ angular.js:16311y.transitionTo @ angular-ui-router-0.2.15.js:7
angular.js:12477
```
```
Error: Maximum call stack size exceeded
<error>
    at Object.error (http://192.168.1.126:8100/lib/angular/angular.js:12477:24)
    at ident.$get (http://192.168.1.126:8100/lib/angular/angular.js:9246:18)
    at Scope.parent.$get.Scope.$broadcast (http://192.168.1.126:8100/lib/angular/angular.js:16313:15)
    at Object.y.transitionTo (http://192.168.1.126:8100/lib/angular-ui-router/angular-ui-router-0.2.15.js:7:17776)
    at Object.y.go (http://192.168.1.126:8100/lib/angular-ui-router/angular-ui-router-0.2.15.js:7:16391)
    at http://192.168.1.126:8100/js/app.js:110:20
    at Scope.parent.$get.Scope.$broadcast (http://192.168.1.126:8100/lib/angular/angular.js:16311:28)
    at Object.y.transitionTo (http://192.168.1.126:8100/lib/angular-ui-router/angular-ui-router-0.2.15.js:7:17776)
    at Object.y.go (http://192.168.1.126:8100/lib/angular-ui-router/angular-ui-router-0.2.15.js:7:16391)
    at http://192.168.1.126:8100/js/app.js:110:20
```

**Comment by eddiemonge** [comment]
You don't have a `url: '/'` defined. Try defining a state for that and see if it works.

**Comment by seesoe** [comment]
Hmm, that still didn't get rid of the 2 errors. I tried
```js
    .state('test', {
        url: '/'
    })
```
and
```js
    .state('home', {
        url: '/',
        templateUrl: 'templates/home.html',
        controller: 'homeController'
    })
```

**Comment by serbiant** [comment]
The only probable issue that can be the reason of errors is this.
AFAIK, it's a bad practice to use `$state.go` in `$stateChangeStart` event. For your purposes, you'd better put $state.go into `resolve`.
```
$rootScope.$on('$stateChangeStart', function (event, toState, toParams, fromState, fromParams) {
        var userInfo = $cookieStore.get('UserData');
// try this check
        if(toState.name) === 'home' return;
        if (!userInfo) {
            if (toState.name !== 'signin') {
                $state.go('signin');
                event.preventDefault();
                return;
            }
        } else {
            $state.go("home");
            event.preventDefault();
            return;
        }
    });
```

**Comment by seesoe** [comment]
Thanks @serbiant for pointing me in the right direction, it looks like `$state.go` does not like to be called when `fromState.name === toState.name` and thus making an infinite loop.

I changed my code to the following
```js
    $rootScope.$on('$stateChangeStart', function (event, toState, toParams, fromState, fromParams) {
        var userInfo = $cookieStore.get('UserData');

        if (!userInfo) {
            if (toState.name !== 'signin') {
                $state.go('signin');
                event.preventDefault();
            }
        } else {
            if(toState.name === 'signin') {
                $state.go('home');
                event.preventDefault();
            }
        }
    });
```
You mind showing me an example of putting `$state.go` in the resolve? (I've only started learning angular a few weeks ago)

**Comment by serbiant** [comment]
@seesoe sorry I was wrong. You are able to use `$state.go` in resolves only with promises.

**Comment by seesoe** [comment]
awesome, thanks
