### ISSUE TITLE
TypeError raised when using ngInclude as a default content for uiView and switching state

### ISSUE THREAD

**Issue by VinceOPS** [angular-ui/ui-router#2463]
Hi UI-router team,

First time I've been around here, so I'd like to take the opportunity to say Thanks for your great work.

I recently posted a [pull request](https://github.com/angular/angular.js/pull/13770) on Angular.js repository for an issue I encountered few days ago. The issue **might** (at least partly) be due to ui-router, that's why I think it's reasonable to create an issue here.

**Version** The error is raised in my ionic project (angular 1.4.3, ui-router 0.2.13) but also with the last version of Angular 1.4.8 and ui-router 0.2.15 (at the time being). 

**Browser** I could reproduce the case with both Chrome and Firefox.

**System** Linux (Debian 8.2), Windows (8.1 and 10)

**Reproducable** Always

I also reproduced it using a **Plunker**: http://plnkr.co/jLspFZOTvkevx25KgxEp

```
TypeError: Cannot read property 'insertBefore' of null
    at forEach.after (https://code.angularjs.org/1.4.8/angular.js:3498:13)
    at Object.JQLite.(anonymous function) [as after] (https://code.angularjs.org/1.4.8/angular.js:3582:17)
    at domInsert (https://code.angularjs.org/1.4.8/angular.js:5095:35)
    at Object.enter (https://code.angularjs.org/1.4.8/angular.js:5258:9)
    at https://code.angularjs.org/1.4.8/angular.js:24404:26
    at publicLinkFn (https://code.angularjs.org/1.4.8/angular.js:7610:29)
    at boundTranscludeFn (https://code.angularjs.org/1.4.8/angular.js:7749:16)
    at controllersBoundTransclude (https://code.angularjs.org/1.4.8/angular.js:8362:18)
    at https://code.angularjs.org/1.4.8/angular.js:24402:27
    at processQueue (https://code.angularjs.org/1.4.8/angular.js:14792:28)
```

And the case is as follows:
Using a ngInclude node in a uiView node in order to display a default content. 

``` html
<div ui-view="myPage">
  <div ng-include="'default-view.html'"></div>
</div>
```

Ther error is raised (in Angular's JQLite) when navigating to a route displaying an other content for the uiView.

**Comment by christopherthielen** [comment]
It seems that wrapping the ng-include div in a second div works around the problem:

```
<div ui-view="myPage">
<div>  <div ng-include="'default-view.html'"></div> </div>
</div>```
