### ISSUE TITLE
install 1.0 alpha via bower or npm

### ISSUE THREAD

**Issue by rolandjitsu** [angular-ui/ui-router#2500]
It looks like the alpha preview is not published anywhere. Is there a way to install it since you advise on starting to migrate?

**Comment by christopherthielen** [comment]
Thanks for letting us know we didn't publish to npm; I'll fix that when I get a spare moment.  

I think bower should work, since it uses github tags.

**Comment by rolandjitsu** [comment]
I'll try it, but is `1.0.0alpha0` semver? Should it not be `1.0.0-alpha.0` (according to [semver.org](http://semver.org)).

**Comment by christopherthielen** [comment]
Good point.  Let me know if you were able to install via bower. We'll make sure to use 1.0.0-alpha.1 for the next release.

**Comment by rolandjitsu** [comment]
If I  `bower install angular-ui-router#1.0.0alpha0` I get a `ECONFLICT Unable to find suitable version for angular-ui-router`.

**Comment by rolandjitsu** [comment]
I get the same for running `bower install git@github.com:angular-ui/ui-router.git#1.0.0alpha0`.

**Comment by christopherthielen** [comment]
BTW, I was able to install from npm using 
`    "angular-ui-router": "1.0.0-alpha0"`

**Comment by christopherthielen** [comment]
I just published `1.0.0-alpha.1` to bower and npm.  Let me know if you have any problems fetching them.

**Comment by WinterPhoenix** [comment]
Is it possible to unpublish version 1.0.0alpha0 from bower? I'm getting an error when running `bower install` on my project even though I changed my dependency to explicitly require 0.2.18.  What I'm seeing is below. My assumption is that bower is still checking the list of all versions published, even though I'm explicitly depending on a fixed version. That seems kind of silly and obviously not this project's problem, but leaving a non-compliant semver version published is something that can be resolved.

> bower angular-ui-router#0.2.18                     error Invalid Version: 1.0.0alpha0
> 
> Stack trace:
> TypeError: Invalid Version: 1.0.0alpha0
>     at new SemVer (path_to_project/node_modules/bower/lib/node_modules/semver/semver.js:273:11)
>     at compare (path_to_project/node_modules/bower/lib/node_modules/semver/semver.js:460:10)
>     at Object.neq (path_to_project/node_modules/bower/lib/node_modules/semver/semver.js:504:10)
>     at GitHubResolver.GitResolver._savePkgMeta (path_to_project/node_modules/bower/lib/core/resolvers/GitResolver.js:209:56)
>     at GitHubResolver._savePkgMeta (path_to_project/node_modules/bower/lib/core/resolvers/GitHubResolver.js:134:53)
>     at _fulfilled (path_to_project/node_modules/bower/lib/node_modules/q/q.js:834:54)
>     at self.promiseDispatch.done (path_to_project/node_modules/bower/lib/node_modules/q/q.js:863:30)
>     at Promise.promise.promiseDispatch (path_to_project/node_modules/bower/lib/node_modules/q/q.js:796:13)
>     at path_to_project/node_modules/bower/lib/node_modules/q/q.js:604:44
>     at runSingle (path_to_project/node_modules/bower/lib/node_modules/q/q.js:137:13)

**Comment by cudasteve** [comment]
We're seeing the same semver error with bower (although builds do seem to succeed maybe 10% of the time, really weird).  In any case, if you could remove or fix the non-compliant semver tag, it would be greatly appreciated.

**Comment by christopherthielen** [comment]
@davidmcclelland @cudasteve I dropped the ball here (because these comments are on a closed issue)

I had no problems installing 0.3.0 using `bower install angular-ui-router`.  Can you provide more details?

I will nuke the alpha0 release from our bower tags, but first I'd like to get more details on the issue.

See new issue https://github.com/angular-ui/ui-router/issues/2776

**Comment by andersco** [comment]
I'm having a similar issue trying to use bower within visual studio to install version 0.3.1:

`PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\Bower.cmd" install angular-ui-router#0.3.1 --force-latest
bower angular#1.5.6         not-cached https://github.com/angular/bower-angular.git#1.5.6
bower angular#1.5.6            resolve https://github.com/angular/bower-angular.git#1.5.6
bower angular-ui-router#0.3.1       not-cached https://github.com/angular-ui/angular-ui-router-bower.git#0.3.1
bower angular-ui-router#0.3.1          resolve https://github.com/angular-ui/angular-ui-router-bower.git#0.3.1
bower angular-ui-router#0.3.1       not-cached https://github.com/angular-ui/angular-ui-router-bower.git#0.3.1
bower angular-ui-router#0.3.1          resolve https://github.com/angular-ui/angular-ui-router-bower.git#0.3.1
bower angular-jwt#0.0.9                 cached https://github.com/auth0/angular-jwt.git#0.0.9
bower angular-jwt#0.0.9               validate 0.0.9 against https://github.com/auth0/angular-jwt.git#0.0.9
bower a0-angular-storage#0.0.15         cached https://github.com/auth0/angular-storage.git#0.0.15
bower a0-angular-storage#0.0.15       validate 0.0.15 against https://github.com/auth0/angular-storage.git#0.0.15
bower angular-ui-router#0.3.1         checkout 0.3.1
bower angular-ui-router#0.3.1         checkout 0.3.1
bower angular#1.5.6                   checkout v1.5.6
bower angular-ui-router#0.3.1            error Invalid Version: 1.0.0alpha0
Stack trace:
TypeError: Invalid Version: 1.0.0alpha0
    at new SemVer (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\semver\semver.js:273:11)
    at compare (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\semver\semver.js:460:10)
    at Object.neq (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\semver\semver.js:504:10)
    at GitHubResolver.GitResolver._savePkgMeta (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\bower\lib\core\resolvers\GitResolver.js:207:56)
    at GitHubResolver._savePkgMeta (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\bower\lib\core\resolvers\GitHubResolver.js:134:53)
    at _fulfilled (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\q\q.js:796:13)
    at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\q\q.js:604:44
    at runSingle (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\q\q.js:137:13)
Console trace:
Error
    at StandardRenderer.error (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\bower\lib\renderers\StandardRenderer.js:83:37)
    at Logger.<anonymous> (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\bower\bin\bower:116:30)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\q\q.js:844:24)
    at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\q\q.js:870:30
    at Promise.when (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\q\q.js:788:41)
System info:
Bower version: 1.7.2
Node version: 5.4.1
OS: Windows_NT 6.1.7601 ia32`

**Comment by origicom** [comment]
Don't know if you guys solved this issue already, but I finally found the solution.

root cause of this problem lays in the Git Wrapper that is included in visual studio. Someway this wrapper can't find the version you set in your bower.json and it always installs the latest version (ie. take the master branch instead of the tagged version.

My solution was simple. Install Git for Windows, find the installation bin and remember the path.
Go to visual studio and add this path as an external tool. 

for example:
in Visual Studio go to:  Tools -> Options -> Projects and Solutions -> External Web Tools

Add the location to your Git for Windows bin directory.
ie. c:\program files\Git\bin

Remove the default entry ($(VSINSTALLDIR)\Web\External\git.

if you do a bower install it will finally download the right version and your problem will be solved
