### ISSUE TITLE
1.0.0alpha0 tag causes bower install to fail

### ISSUE THREAD

**Issue by christopherthielen** [angular-ui/ui-router#2776]
See #2500 and https://github.com/bower/bower/issues/2266

**Comment by christopherthielen** [comment]
Suggested fix: remove tag from bower

**Comment by cudasteve** [comment]
Sorry, I'm not able to reproduce locally anymore and we've already switched over to npm, which seems to be working much more reliably.

**Comment by davidmcclelland** [comment]
@christopherthielen As @cudasteve mentioned on the linked bower issue, it only ever seemed to happen on our build server as well. Our bower.json file failed when using `"angular-ui-router": "0.2.18"`, but when I changed it to `
    "angular-ui-router": "https://github.com/angular-ui/ui-router.git#0.2.18",` it seemed to resolve the problem. I'm fairly confident that the invalid semver tag was the problem, as it had been building just fine and then stopped suddenly. When I searched around, I noticed that ui-router had very recently published with the invalid semver tag.

It seems like this should be something that bower handles better - I wasn't using the ~ or ^ operators and the version that I was requesting had already been published correctly. That said, I appreciate your willingness to help out in the near term by unpublishing it.

Like @cudasteve, I only saw it every so often. I've changed the bower file back to using just `0.2.18" - if it fails again I'll update this issue.

Thanks!

**Comment by wally777** [comment]
I also cannot install any version of "angular-ui-router" using bower:

bower angular-ui-router#0.2.18       not-cached https://github.com/angular-ui/angular-ui-router-bower.git#0.2.18
bower angular-ui-router#0.2.18          resolve https://github.com/angular-ui/angular-ui-router-bower.git#0.2.18
bower angular-ui-router#0.2.18         checkout 0.2.18
bower angular-ui-router#0.2.18            error Invalid Version: 1.0.0alpha0

**Comment by cudasteve** [comment]
@wally777 did this happen just now?  That tag shouldn't exist anymore.  Have you installed this previously on your machine and maybe it's just cached?  Can you `bower cache clean` and try again?

**Comment by christopherthielen** [comment]
I haven't nuked the tag yet.  I'll do so now.

**Comment by EjaYF** [comment]
I am still seeing the invalid tag and my bower still has issues with this... I even tried `bower cache clean` but that still doesn't work:

`bower angular-ui-router#0.3.0                        error Invalid Version: 1.0.0alpha0
Stack trace:
TypeError: Invalid Version: 1.0.0alpha0
    at new SemVer (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\bower\lib\node_modules\semver\semver.js:273:11)
    at compare (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\bower\lib\node_modules\semver\semver.js:460:10)
    at Object.neq (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\bower\lib\node_modules\semver\semver.js:504:10)
`

**Comment by matthewpavkov** [comment]
I'm also seeing this issue. We're using bower through Visual Studio 2015. In our `bower.json` we have `"angular-ui-router": "0.2.14"`, yet we're seeing `bower angular-ui-router#0.2.14       error Invalid Version: 1.0.0alpha0`. This is as of today - also, this is on a fresh install of Windows/Visual Studio/etc. Any thoughts?

**Comment by andersco** [comment]
I had the same issue in VS2015 but @davidmcclelland's solution fixed it for me. I changed
`"angular-ui-router": "0.3.1",`
to
`"angular-ui-router": "https://github.com/angular-ui/ui-router.git#0.3.1",`

**Comment by kulwantyadav101** [comment]
I am also facing the issue.
bower angular-ui-router#0.2.15                               error Invalid Version: 1.0.0alpha0
Stack trace:
TypeError: Invalid Version: 1.0.0alpha0
    at new SemVer (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\semver\semver.js:273:11)
    at compare (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\semver\semver.js:460:10)
    at Object.neq (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\semver\semver.js:504:10)
    at GitHubResolver.GitResolver._savePkgMeta (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\bower\lib\core\resolvers\GitResolver.js:207:56)
    at GitHubResolver._savePkgMeta (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\bower\lib\core\resolvers\GitHubResolver.js:134:53)
    at _fulfilled (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\q\q.js:796:13)
    at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\q\q.js:604:44
    at runSingle (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\q\q.js:137:13)
Console trace:
Error
    at StandardRenderer.error (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\bower\lib\renderers\StandardRenderer.js:83:37)
    at Logger.<anonymous> (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\bower\bin\bower:116:30)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\q\q.js:844:24)
    at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\q\q.js:870:30
    at Promise.when (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\q\q.js:788:41)
System info:
Bower version: 1.7.2
Node version: 5.4.1

**Comment by christopherthielen** [comment]
There's a pretty obvious pattern here:

> EjaYF commented on Jun 7
> Microsoft Visual Studio 14.0

> matthewpavkov commented on Jun 14
> We're using bower through Visual Studio 2015.

> andersco commented on Jun 14
> I had the same issue in VS2015

> kulwantyadav101 commented 7 hours ago
> Microsoft Visual Studio 14.0


We moved our published bower released from `https://github.com/angular-ui/ui-router` to a totally different repository: `https://github.com/angular-ui/angular-ui-router-bower.git` which definitely does not have the `alpha0` tag.

I suspect Visual Studio is not picking the new location from the bower registry and is trying to install from `angular-ui/ui-router` (defunct).  I don't think there's much that I can do further on my end to address this.  

Try forcing your bower dependency to: 
`"angular-ui-router": "https://github.com/angular-ui/angular-ui-router-bower.git#0.3.1"`

I simply cannot reproduce this.  It works fine for me:

```
./node_modules/bower/bin/bower install angular-ui-router#0.2.15 [12:55PM ]
(node:78747) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
bower not-cached    https://github.com/angular-ui/angular-ui-router-bower.git#0.2.15
bower resolve       https://github.com/angular-ui/angular-ui-router-bower.git#0.2.15
bower checkout      angular-ui-router#0.2.15
bower resolved      https://github.com/angular-ui/angular-ui-router-bower.git#0.2.15
bower cached        https://github.com/angular/bower-angular.git#1.5.5
bower validate      1.5.5 against https://github.com/angular/bower-angular.git#>= 1.0.8
bower new           version for https://github.com/angular/bower-angular.git#>= 1.0.8
bower resolve       https://github.com/angular/bower-angular.git#>= 1.0.8
bower checkout      angular#v1.5.8
bower resolved      https://github.com/angular/bower-angular.git#1.5.8
bower install       angular-ui-router#0.2.15
bower install       angular#1.5.8

angular-ui-router#0.2.15 bower_components/angular-ui-router
└── angular#1.5.8

angular#1.5.8 bower_components/angular

```

**Comment by christopherthielen** [comment]
<img width="695" alt="screen shot 2016-10-07 at 1 17 39 pm" src="https://cloud.githubusercontent.com/assets/2053478/19200789/7725b198-8c90-11e6-914a-be5dff19dd16.png">


Are you guys using this: https://visualstudiogallery.msdn.microsoft.com/753b9720-1638-4f9a-ad8d-2c45a410fd74 ?

**Comment by christopherthielen** [comment]
What happens when you run this:
```
$ bower lookup angular-ui-router                                                                                                    [ 
angular-ui-router https://github.com/angular-ui/angular-ui-router-bower.git
```

If it says `https://github.com/angular-ui/ui-router.git` then that's a problem.

**Comment by cariquitanmac** [comment]
@christopherthielen   I'm still experiencing the issue.

> Try forcing your bower dependency to: 
> "angular-ui-router": "https://github.com/angular-ui/angular-ui-router-bower.git#0.3.1"

I also tried this one with no luck.
As a temporary fix for now, I'd downloaded the js file manually and include it in my project.

**Comment by christopherthielen** [comment]
Wish I could help, but there's not much I can do.  This is obviously some problem with MS Visual Studio's bower support.  If anyone with access to Visual Studio comes up with a solution, or some action the ui-router team can take, please post it!

**Comment by origicom** [comment]
Don't know if you guys solved this issue already, but I finally found the solution.

root cause of this problem lays in the Git Wrapper that is included in visual studio. Someway this wrapper can't find the version you set in your bower.json and it always installs the latest version (ie. take the master branch instead of the tagged version.

My solution was simple. Install Git for Windows, find the installation bin and remember the path.
Go to visual studio and add this path as an external tool. 

for example:
in Visual Studio go to:  Tools -> Options -> Projects and Solutions -> External Web Tools

Add the location to your Git for Windows bin directory.
ie. c:\program files\Git\bin

Remove the default entry ($(VSINSTALLDIR)\Web\External\git.

if you do a bower install it will finally download the right version and your problem will be solved

**Comment by christopherthielen** [comment]
Thanks @origicom !  

I'm surprised it had to do with the git wrapper.

**Comment by cariquitanmac** [comment]
@origicom  Thanks for the resolution.
I will try this once I get back to asp net core.

**Comment by kulwantyadav101** [comment]
Thanks @origicom 
It's working for me.
