### ISSUE TITLE
Angular 2 Resolve dependencies injection

### ISSUE THREAD

**Issue by demisx** [angular-ui/ui-router#2907]
Hello. I have the following state definition with Angular 2 resolve style:

```js
...
import { Center } from './center.model'

export const centerStates: Ng2StateDeclaration[] = [
  {
    name: 'app.centers',
    url: '/centers',
    views: {
      $default: { component: ListCentersComponent },
    },
    resolve: [
      {
        provide: 'centerList',
        useFactory: (Center: Center) => Center.findAll(),
        deps: [Center] // <- errors out with no provider for Center.
      }
    ]
  }
...
];
```

Trying to enter this state results in `No provider for Center!` with the following DI error written to browser console:

```
ui-router-ng2.js:5736 Error: DI Exception
    at NoProviderError.BaseException [as constructor] (http://localhost:8030/vendor/@angular/core/bundles/core.umd.js:4412:27)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:8030/vendor/@angular/core/bundles/core.umd.js:4529:20)
    at new NoProviderError (http://localhost:8030/vendor/@angular/core/bundles/core.umd.js:4565:20)
    at ReflectiveInjector_._throwOrNull (http://localhost:8030/vendor/@angular/core/bundles/core.umd.js:6461:23)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:8030/vendor/@angular/core/bundles/core.umd.js:6489:29)
    at ReflectiveInjector_._getByKey (http://localhost:8030/vendor/@angular/core/bundles/core.umd.js:6452:29)
    at ReflectiveInjector_.get (http://localhost:8030/vendor/@angular/core/bundles/core.umd.js:6261:25)
    at getDependency (http://localhost:8030/vendor/ui-router-ng2/_bundles/ui-router-ng2.js:2505:67)
    at Array.map (native)
    at ResolveContext.getDependencies (http://localhost:8030/vendor/ui-router-ng2/_bundles/ui-router-ng2.js:2511:33)$defaultErrorHandler @ ui-router-ng2.js:5736(anonymous function) @ ui-router-ng2.js:6029ZoneDelegate.invoke @ zone.js:323onInvoke @ core.umd.js:9100ZoneDelegate.invoke @ zone.js:322Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356onInvokeTask @ core.umd.js:9091ZoneDelegate.invokeTask @ zone.js:355Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
```

I can make this error go away by adding `Center` to the bootstrap dependency as shown below, but that doesn't seem to feel right to do it at the root level. I'd rather do it at a view or component level, so it's scoped to that particular injector. Is this possible?

```js
...
bootstrap(UIView, [
  provide(LocationStrategy, { useClass: PathLocationStrategy }),
  provide(PlatformLocation, { useClass: BrowserPlatformLocation }),
  ...UIROUTER_PROVIDERS,
  ...HTTP_PROVIDERS,
  provide(UIRouterConfig, { useClass: AppUIRouterConfig }),
  Center // <- Makes the error go away, but doesn't feel right.
])
```

Thank you.

**Comment by christopherthielen** [comment]
If `Center` is a stateless service, you can just import it:

```js
...
import { Center } from './center.model'

export const centerStates: Ng2StateDeclaration[] = [
  {
    name: 'app.centers',
    url: '/centers',
    views: {
      $default: { component: ListCentersComponent },
    },
    resolve: [
      {
        provide: 'centerList',
        useFactory: () => Center.findAll(),
      }
    ]
  }
...
];
```

If it's stateful (you need an instance)  you can add it to the DI tree as its own resolve.  It will be available for injection into any child states and their components.


```js
...
import { Center } from './center.model'

export const centerStates: Ng2StateDeclaration[] = [
  {
    name: 'app.centers',
    url: '/centers',
    views: {
      $default: { component: ListCentersComponent },
    },
    resolve: [
      { provide: Center, useClass: Center },
      {
        provide: 'centerList',
        useFactory: (Center: Center) => Center.findAll(),
        deps: [Center]
      }
    ]
  }
...
];
```

**Comment by demisx** [comment]
@christopherthielen Thank you for the direction. If I am understanding right, I believe I need to stick with the second option, so the `Center` model can be injected as a mock in unit tests at some point. I've tried this approach and the "no provider error" went away. However, there is a new error now since another service that `Center` depends on no longer is getting injected:

```js
// in center.states.ts
export const centerStates: Ng2StateDeclaration[] = [
  {
    name: 'app.centers',
    url: '/centers',
    views: {
      $default: { component: ListCentersComponent },
    },
    resolve: [
      { provide: Center, useClass: Center, deps: [DataStoreService] },
      {
        provide: 'centerList',
        useFactory: (Center: Center) => {
          return Center.findAll();
        },
        deps: [Center]
      }
    ]
  }
];

// in center.ts
...
@Injectable()
export class Center {
  private mapper: Mapper;
  private store: DataStore;

  constructor(dss: DataStoreService) {
    console.debug('-> dss injected:', dss); // <- this is undefined now
    this.store = dss.getStore(); // <- TypeError: Cannot read property 'getStore' of undefined
  }
... ... ...
```

Do I need to do anything special for the `DataStoreService` to be injected again? Thank you. Trying to wrap my head around this DI thing.

**Comment by christopherthielen** [comment]
ng2 rc5 introduces "App Modules".

https://angular.io/docs/ts/latest/guide/ngmodule.html#!#application-scoped-providers

## Application-scoped Providers

> The ContactService provider is application-scoped because Angular registers a module's providers with the application's root injector.

> Architecturally, the ContactService belongs to the Contact business domain. Classes in other domains don't need the ContactService and shouldn't inject it.

> We might expect Angular to offer a module-scoping mechanism to enforce this design. It doesn't. Angular module instances, unlike components, do not have their own injectors so they can't have their own provider scopes.

**Comment by christopherthielen** [comment]
Closing, because I think the question has been answered.  Feel free to continue the conversation though.
