### ISSUE TITLE
angularjs component + ui-router + requirejs testing

### ISSUE THREAD

**Issue by xzguan** [angular-ui/ui-router#3226]
try to make use of the nice feature of routing by component

uisng  **AngularJS v1.6.0** and **angular-ui-router @version v0.3.1** 
I could make component routing work,but the <ui-view></ui-view> couldn't load  the content correctly

index.html
![image](https://cloud.githubusercontent.com/assets/11084924/21447976/bc111486-c8aa-11e6-9186-4fbe88cf439a.png)

![image](https://cloud.githubusercontent.com/assets/11084924/21448040/dc9b42b6-c8ab-11e6-99f5-4cfdee839a6c.png)

Someone said that it was caused by angular-ui-router old version, it should be >v1.x . I tried to change it to @version v1.0.0-alpha.4, a serious trouble happened 

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module ui.router due to:
Error: [$injector:nomod] Module 'ui.router' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.6.0/$injector/nomod?p0=ui.router
    at http://localhost:54538/scripts/angular-1.6.0/angular.js:68:12
    at http://localhost:54538/scripts/angular-1.6.0/angular.js:2183:17
    at ensure (http://localhost:54538/scripts/angular-1.6.0/angular.js:2107:38)
    at module (http://localhost:54538/scripts/angular-1.6.0/angular.js:2181:14)
    at http://localhost:54538/scripts/angular-1.6.0/angular.js:4733:22
    at forEach (http://localhost:54538/scripts/angular-1.6.0/angular.js:357:20)
    at loadModules (http://localhost:54538/scripts/angular-1.6.0/angular.js:4717:5)
    at http://localhost:54538/scripts/angular-1.6.0/angular.js:4734:40
    at forEach (http://localhost:54538/scripts/angular-1.6.0/angular.js:357:20)
    at loadModules (http://localhost:54538/scripts/angular-1.6.0/angular.js:4717:5)
http://errors.angularjs.org/1.6.0/$injector/modulerr?p0=ui.router&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'ui.router'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.0%2F%24injector%2Fnomod%3Fp0%3Dui.router%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A54538%2Fscripts%2Fangular-1.6.0%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A54538%2Fscripts%2Fangular-1.6.0%2Fangular.js%3A2183%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Flocalhost%3A54538%2Fscripts%2Fangular-1.6.0%2Fangular.js%3A2107%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Flocalhost%3A54538%2Fscripts%2Fangular-1.6.0%2Fangular.js%3A2181%3A14)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A54538%2Fscripts%2Fangular-1.6.0%2Fangular.js%3A4733%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A54538%2Fscripts%2Fangular-1.6.0%2Fangular.js%3A357%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A54538%2Fscripts%2Fangular-1.6.0%2Fangular.js%3A4717%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A54538%2Fscripts%2Fangular-1.6.0%2Fangular.js%3A4734%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A54538%2Fscripts%2Fangular-1.6.0%2Fangular.js%3A357%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A54538%2Fscripts%2Fangular-1.6.0%2Fangular.js%3A4717%3A5)
    at http://localhost:54538/scripts/angular-1.6.0/angular.js:68:12
    at http://localhost:54538/scripts/angular-1.6.0/angular.js:4756:15
    at forEach (http://localhost:54538/scripts/angular-1.6.0/angular.js:357:20)
    at loadModules (http://localhost:54538/scripts/angular-1.6.0/angular.js:4717:5)
    at http://localhost:54538/scripts/angular-1.6.0/angular.js:4734:40
    at forEach (http://localhost:54538/scripts/angular-1.6.0/angular.js:357:20)
gular.js:4734:40    at forEach (http://localhost:54538/scripts/angular-1.6.0/angular.js:357:20)
```

**Could anyone give some help? thanks**

*comHeroList: a component module: 

## main.js
```js
require.config({
    baseUrl: "/Apps/HeroTS",
    paths: {
        "angular": "../../scripts/angular-1.6.0/angular",
        "ui.router":"angular-ui-router"
    },
    shim: {
        "angular": {
            "exports": "angular"
        },
        'ui.router': {
            deps: ['angular']
        },
        "app": {
            deps:['angular','ui.router',"coremodule"]
        }
    }
});
require(["angular","coremodule","ui.router"], function (angular) {
    angular.element(document).ready(() => {
        angular.bootstrap(document, ["app"]);
    })
 }) 
```

## cordmodule (from compiling type script)

```js
define(["require", "exports", "angular", "comHeroList"], function (require, exports, angular, heros) {
    "use strict";
     exports.app = angular.module("app", ["ui.router"]);
    exports.app.config(heros.config);
    exports.app.component('heroList', new heros.heroList());
    exports.app.component('heroDetail', new heros.heroDetail());
    exports.app.component('editableField', new heros.editableField());
    exports.app.component('about', new heros.about());
    
});
```

**Comment by christopherthielen** [comment]
Sorry, I hate to close this without helping, but we really don't have the bandwidth, nor expertise to help with requirejs issues.  I suggest asking your question on stackoverflow.  Thanks for trying ui-router!

http://bit.ly/UIR-SOF

**Comment by christopherthielen** [comment]
Example requireJS
https://github.com/christopherthielen/angular-require-uiRouter
