### ISSUE TITLE
Upgrading from 0.4 to 1.0.0-rc.1 give me a undefined error

### ISSUE THREAD

**Issue by Xarkam** [angular-ui/ui-router#3283]
Hello, I try to upgrade ui-router to 1.0rc but juste I use latest version I receive this error on my app
```
angular.min.js:14328 TypeError: Cannot read property '@' of undefined
    at updateView (http://192.168.0.5:8100/dist/ionic/js/ionic-angular.min.js:12206:69)
    at Object.<anonymous> (http://192.168.0.5:8100/dist/ionic/js/ionic-angular.min.js:12201:9)
    at http://192.168.0.5:8100/dist/angular/js/angular.min.js:1291:18
    at invokeLinkFn (http://192.168.0.5:8100/dist/angular/js/angular.min.js:10252:9)
    at nodeLinkFn (http://192.168.0.5:8100/dist/angular/js/angular.min.js:9641:11)
    at compositeLinkFn (http://192.168.0.5:8100/dist/angular/js/angular.min.js:8881:13)
    at compositeLinkFn (http://192.168.0.5:8100/dist/angular/js/angular.min.js:8884:13)
    at publicLinkFn (http://192.168.0.5:8100/dist/angular/js/angular.min.js:8746:30)
    at http://192.168.0.5:8100/dist/angular/js/angular.min.js:1843:27
    at Scope.$eval (http://192.168.0.5:8100/dist/angular/js/angular.min.js:17972:28) <ion-nav-view class="view-container" nav-view-transition="ios">

```
And I don't understand what is the problem.

Thank for your help.

**Comment by christopherthielen** [comment]
Based on [this comment](https://github.com/driftyco/ionic/issues/9843#issuecomment-270177654) I do not think ionic works with ui-router 1.0
