### ISSUE TITLE
After updating - Error: [$compile:tpload] Failed to load template

### ISSUE THREAD

**Issue by kspearrin** [angular-ui/ui-router#3354]
After updating from angular 1.5.6 => 1.6.2 and ui-router 0.3.1 => 0.4.2 I am now getting this error:

```
Error: [$compile:tpload] Failed to load template: app/views/frontendLayout.html (HTTP status: undefined undefined)
http://errors.angularjs.org/1.6.2/$compile/tpload?p0=app%2Fviews%2FfrontendLayout.html&p1=undefined&p2=undefined
    at http://localhost:4011/lib/angular/angular.js:68:12
    at handleError (http://localhost:4011/lib/angular/angular.js:19778:20)
    at processQueue (http://localhost:4011/lib/angular/angular.js:16689:37)
    at http://localhost:4011/lib/angular/angular.js:16733:27
    at Scope.$eval (http://localhost:4011/lib/angular/angular.js:18017:28)
    at Scope.$digest (http://localhost:4011/lib/angular/angular.js:17827:31)
    at Scope.$apply (http://localhost:4011/lib/angular/angular.js:18125:24)
    at bootstrapApply (http://localhost:4011/lib/angular/angular.js:1845:15)
    at Object.invoke (http://localhost:4011/lib/angular/angular.js:4862:19)
    at doBootstrap (http://localhost:4011/lib/angular/angular.js:1843:14) undefined
```

Config
===========

```
    .config(function ($stateProvider, $urlRouterProvider, $httpProvider, jwtInterceptorProvider,
        $uibTooltipProvider, toastrConfig, $locationProvider) {
        $locationProvider.hashPrefix('');


[...]

        $urlRouterProvider.otherwise('/');

[...]

        $stateProvider
            .state('frontend', {
                templateUrl: 'app/views/frontendLayout.html',
                abstract: true,
                data: {
                    authorize: false
                }
            })
            .state('frontend.login', {
                templateUrl: 'app/accounts/views/accountsLogin.html',
                controller: 'accountsLoginController',
                data: {
                    bodyClass: 'login-page'
                }
            })
            .state('frontend.login.info', {
                url: '^/',
                templateUrl: 'app/accounts/views/accountsLoginInfo.html',
                data: {
                    pageTitle: 'Log In'
                }
            })
            .state('frontend.login.twoFactor', {
                url: '^/two-factor',
                templateUrl: 'app/accounts/views/accountsLoginTwoFactor.html',
                data: {
                    pageTitle: 'Log In (Two Factor)',
                    authorizeTwoFactor: true
                }
            })
            .state('frontend.logout', {
                url: '^/logout',
                controller: 'accountsLogoutController',
                data: {
                    authorize: true
                }
            })

[...]
```

Any ideas?

**Comment by christopherthielen** [comment]
[0.4 uses $templateRequest](https://github.com/angular-ui/ui-router/releases/tag/0.4.0)

you can try switching back to  $http as mentioned in the release notes.

**Comment by kspearrin** [comment]
@christopherthielen 

I did see that mentioned in the release notes, however, when I try to use `$templateFactoryProvider.shouldUnsafelyUseHttp(true)` I get a different issues. I'd prefer to use this new `$templateRequest` way but I couldn't find anything documented that showed me how to change what I have to work with `$templateRequest`.

Anyways, I have created a branch in our codebase that reproduces the problem for you: 

https://github.com/bitwarden/web/tree/update

```
git clone git@github.com:bitwarden/web.git
git checkout update
npm install
gulp serve
```

Access the website at http://localhost:4011 (you will see the issue here).

```
"Error: [$compile:tpload] Failed to load template: app/views/frontendLayout.html (HTTP status: undefined undefined)
http://errors.angularjs.org/1.6.2/$compile/tpload?p0=app%2Fviews%2FfrontendLayout.html&p1=undefined&p2=undefined
minErr/<@http://localhost:4011/lib/angular/angular.js:68:12
handleError@http://localhost:4011/lib/angular/angular.js:19778:20
processQueue@http://localhost:4011/lib/angular/angular.js:16689:37
scheduleProcessQueue/<@http://localhost:4011/lib/angular/angular.js:16733:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:4011/lib/angular/angular.js:18017:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:4011/lib/angular/angular.js:17827:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:4011/lib/angular/angular.js:18125:13
bootstrapApply@http://localhost:4011/lib/angular/angular.js:1845:9
invoke@http://localhost:4011/lib/angular/angular.js:4862:16
bootstrap/doBootstrap@http://localhost:4011/lib/angular/angular.js:1843:5
bootstrap@http://localhost:4011/lib/angular/angular.js:1863:12
angularInit@http://localhost:4011/lib/angular/angular.js:1748:5
@http://localhost:4011/lib/angular/angular.js:33129:5
jQuery.Callbacks/fire@http://localhost:4011/lib/jquery/jquery.js:3187:11
jQuery.Callbacks/self.fireWith@http://localhost:4011/lib/jquery/jquery.js:3317:7
.ready@http://localhost:4011/lib/jquery/jquery.js:3536:3
completed@http://localhost:4011/lib/jquery/jquery.js:3552:2
" undefined
```

If I uncomment the `$templateFactoryProvider.shouldUnsafelyUseHttp(true)` option mentioned in the release notes I get no error but no template file loads (just blank page).

**Comment by christopherthielen** [comment]
This is caused by your angular-jwt code throwing an exception while trying to inject a function.  It's due to no `config` registered with DI.

<img width="754" alt="screen shot 2017-03-21 at 8 32 29 pm" src="https://cloud.githubusercontent.com/assets/2053478/24178186/9341b8d8-0e75-11e7-8d31-3edbba25ebaa.png">


<img width="633" alt="screen shot 2017-03-21 at 8 32 42 pm" src="https://cloud.githubusercontent.com/assets/2053478/24178187/965cedb2-0e75-11e7-8da7-1bde410333e2.png">

**Comment by kspearrin** [comment]
@christopherthielen Wow, I'm really sorry about that. I hope I didn't waste too much of your time. Thanks.

**Comment by christopherthielen** [comment]
No problem

**Comment by xingwen1987** [comment]
And，How to Fix it？
