### ISSUE TITLE
V1.1.0 - TypeError: Cannot read properties of undefined (reading 'inherit')  

### ISSUE THREAD

**Issue by p3pp8** [angular-ui/ui-router#3851]
After updating to version 1.1.0 i'm not able to run my app anymore. I use AngularJS 1.8.3.

```
TypeError: Cannot read properties of undefined (reading 'inherit')
    at StateParams.$inherit (factory.js:63:9)
    at StateService.href (factory.js:63:9)
    at BaseUrlRule.handler (factory.js:63:9)
    at UrlService.sync (factory.js:63:9)
    at factory.js:63:9
    at factory.js:63:9
    at Array.forEach (<anonymous>)
    at factory.js:63:9
    at Scope.$broadcast (factory.js:63:9)
    at afterLocationChange (factory.js:63:9)
    at factory.js:63:9
    at Scope.$digest (factory.js:63:9)
    at Scope.$apply (factory.js:63:9)
    at bootstrapApply (factory.js:63:9)
    at Object.invoke (factory.js:63:9)
    at doBootstrap (factory.js:63:9)
(
```
I did not find any changelog and/or migration instructions. Any help is really appreciated.

**Comment by p3pp8** [comment]
Hello, thanx for the answer. I did it, i added "@uirouter/core": "^6.1.0" dep into package.json but still have the same error. Do i need to inject it into the angolarjs scope?

**Comment by wawyed** [comment]
Are you using any other packages from uirouter?

**Comment by p3pp8** [comment]
Yes:

import { RejectType } from '@uirouter/angularjs';

**Comment by wawyed** [comment]
Which version did you update from?

**Comment by p3pp8** [comment]
1.0.30

**Comment by wawyed** [comment]
I can't see anything that'd make it break. Can you try uirouter/core 6.0.8?

**Comment by p3pp8** [comment]
Just tested using core 6.0.8 and that fixed the problem, works like a charm!

**Comment by p3pp8** [comment]
6.0.9 breaks as for 6.1.0

**Comment by wawyed** [comment]
I think I found out what the problem is. Do you have params declarations as strings instead of objects?

**Comment by p3pp8** [comment]
Ok, i'm going to clenaup my code! Thank you!!!!

**Comment by wawyed** [comment]
Well, I think your case is still supported so I'll add a fix for your case!

**Comment by wawyed** [comment]
@p3pp8 I'm having some issues reproducing the issue in the unit tests. Would you be able to send me a basic state declaration structure that makes this fail? So that I can test my fix.

**Comment by p3pp8** [comment]
Hello @wawyed, the example in the post above is extracted from my project (with some renaming) and is a basic state declaration with default params set to null. I think they should've been declared like this:

```
$stateProvider
        .state('myStateName', {
            url: '/myPage',
            params: {
                a: { value: null },
                b: { value: null }
            }
        });
```

Thank you for the support!

**Comment by wawyed** [comment]
If you change it as above the error disappears?

**Comment by wawyed** [comment]
We have unit tests that test such functionality but they pass

**Comment by p3pp8** [comment]
I'm going to try!

**Comment by p3pp8** [comment]
Nothing to do, i've changed all params to have { value: null } instead of null but the error is still there...

**Comment by wawyed** [comment]
Okay... so it's not that.. would you be able to put a breakpoint where it errors and see which param is trying to access?

**Comment by p3pp8** [comment]
The project is very complex and loads many angular components with states, i'll try to do my best but it's not as simple as put a breakpoint

**Comment by christ182** [comment]
The loop in stateParams.js kept adding the word 'chunk' in parentParamsKeys. 
(node_modules/@uirouter/core/lib-esm/params/stateParams.js)

I don't know what causes that, but I changed the loop from 
`
for (let j in parentParamsKeys) {
    if (parentParams[parentParamsKeys[j]].inherit == false || inheritList.indexOf(parentParamsKeys[j]) >= 0)
        continue;
    inheritList.push(parentParamsKeys[j]);
    inherited[parentParamsKeys[j]] = this[parentParamsKeys[j]];
}
`

to 

`
parentParamsKeys.forEach(j => {
    if (parentParams[j].inherit == false || inheritList.indexOf(j) >= 0)
        return;
    inheritList.push(parentParamsKeys[j]);
    inherited[parentParamsKeys[j]] = this[parentParamsKeys[j]];
});
`
now it works.

**Comment by p3pp8** [comment]
I think i have to wait for a new release, but that's not a problem. Thank you guys!

**Comment by wawyed** [comment]
@christ182 can you inspect parentParamsKeys, check Object.keys(parentParamsKeys) wondering if for some reason there's some enumerable properties added to that array?

**Comment by christ182** [comment]
@wawyed Object.keys is working as expected. It's the loop that does not behave properly.

**Comment by christ182** [comment]
I found the reason for mine.

```
                        Array.prototype.chunk = function(n) {
                            if (!this.length) {
                                return [];
                            }
                            return [this.slice(0, n)].concat(
                                this.slice(n).chunk(n)
                            );
                        };```

```for(var i in parents)``` includes functions as keys. 

Although, I have this Array.prototype.chunk code in for some time now. I don't understand how it suddenly broke.

**Comment by wawyed** [comment]
The reason I said Object.keys() it's because it retrieves the enumerable properties of the array. I wasn't referring to the existing Object.keys.

Regardless I think I have a fix based on your latest comment.

**Comment by wawyed** [comment]
I do suggest though that you use Object.defineProperty() instead and make chunk non enumerable to avoid further issues.

**Comment by ckLocal** [comment]
@wawyed Can V1.1.0 be released as soon as possible?

**Comment by wawyed** [comment]
@ckLocal  is this not what you need? https://www.npmjs.com/package/@uirouter/angularjs/v/1.1.0

**Comment by ckLocal** [comment]
@wawyed  Yeah, this is what I want, that's great.

**Comment by EoinGriffin-AI** [comment]
Hi, I'm running into this same error and I don't see a similarity to @p3pp8's configuration.
Note the value of `j` is `'clear'` here. Seems like that's referencing the clear prototype method of the parentParamsKeys array... but why?

![image](https://github.com/angular-ui/ui-router/assets/6333375/83f1dc44-3dba-42d1-94df-5844c9429860)

Here's where my states are defined. Is there an incompatibility here? I'm upgrading from angular-ui-router 0.4.2 to @uirouter/angularjs 1.1.0 (yes, this is a legacy app that I must support)

```
(function () {
    'use strict';

    var theModule = angular.module('ai.fieldData', [
        // third-party modules
        'ng',
        'ngAnimate',
        'ngAria',
        'ngResource',
        'ngMessages',
        'ui.router',
        'ui.bootstrap',
        'ui.bootstrap.modal',
        'kendo.directives',

        // modules from common app
        'ai.core',
        'ai.directives',
        'ai.directives.upload',
        'ai.filters',
        'ai.services',
        'ngGrid',
        'ai.common.templateCache',
        'ai.directives.expander',

        // modules from field-data app
        'ai.fieldData.templateCache',
        'ai.fieldData.application.constants',
        'ai.fieldData.files',
        'ai.fieldData.monitoring',
        'ai.fieldData.activities',
        'ai.fieldData.activityTree',
        'ai.fieldData.locations',
        'ai.fieldData.navigation',
        'ai.fieldData.visits',
        'ai.fieldData.shared',
        'ai.fieldData.applicationConfiguration',
        'ai.fieldData.exceptionConfiguration',
        'ai.fieldData.corrections',
        'ai.fieldData.levelSurvey',
        'ai.fieldData.verticalReferences'
    ]);

    theModule.config(function ($stateProvider, $urlRouterProvider) {
        $stateProvider
            .state('app', {
                url: '',
                templateUrl: 'source/application/application.html',
                controller: 'FieldDataController',
                resolve: {
                    applicationData: function(ApplicationInitializationService) {
                        return ApplicationInitializationService.getApplicationData();
                    }
                }
            })
            .state('app.formContainer', {
                abstract: true,
                url: '/locations/:locationId/visits',
                templateUrl: 'source/application/form-container.html',
                controller: 'FormController',
                resolve: {
                    channels: function(ApplicationInitializationService) {
                        return ApplicationInitializationService.getChannels();
                    }
                }
            })
            .state('app.formContainer.form', {
                abstract: true,
                views: {
                    'navigationPanel@app': {
                        templateUrl: 'source/navigation/navigation-panel.html'
                    },
                    'visitHeader@app': {
                        templateUrl: 'source/shared/partials/visit-header-form.html'
                    },
                    'status@app.formContainer': {
                        templateUrl: 'source/directives/notification/ai-notification-template.html'
                    }
                }
            })
            .state('app.nonformContainer', {
                abstract: true,
                url: '/locations/:locationId/visits/:visitId',
                templateUrl: 'source/application/nonform-container.html'
            })
            .state('app.nonformContainer.nonform', {
                abstract: true,
                views: {
                    'navigationPanel@app': {
                        templateUrl: 'source/navigation/navigation-panel.html'
                    },
                    'visitHeader@app': {
                        templateUrl: 'source/shared/partials/visit-header-nonform.html'
                    },
                    'status@app.nonformContainer': {
                        templateUrl: 'source/directives/notification/ai-notification-template.html'
                    }
                }
            });

        $urlRouterProvider.otherwise('');
    });
}());
```

**Comment by EoinGriffin-AI** [comment]
Indeed that `'clear'` is an array prototype method... how could I have possibly misconfigured my states to make this happen?

![image](https://github.com/angular-ui/ui-router/assets/6333375/8007cce6-9dad-4cb6-a401-1f377ba44e64)

**Comment by wawyed** [comment]
@EoinGriffin-AI  You shouldn't make custom methods into prototype enumerable. Can you show me the code that adds those methods?

**Comment by EoinGriffin-AI** [comment]
> @EoinGriffin-AI  You shouldn't make custom methods into prototype enumerable. Can you show me the code that adds those methods?

Ah you're right, thanks for pointing out that they're non-standard functions. It's some old custom code added many years ago to our codebase. I can change their definitions to not be enumerable.
