### ISSUE TITLE
Transclusion on UI view not working on IE9-10-11

### ISSUE THREAD

**Issue by mimo84** [angular-ui/ui-router#615]
On IE9-10-11 if you put some html content into an ui-view directive, the content is correctly shown at the first attempt, but not when you come back to the same status. The same code works fine on Firefox and Chrome.

I created a plunker to show the issue:
http://plnkr.co/edit/hz6jY4Jus7OAj3YXeboH?p=preview

This is the error I get:

Error: Invalid argument.
   at buildFragment (http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js:5:22624)
   at domManip (http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js:5:20986)
   at append (http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js:5:18973)
   at restore (http://run.plnkr.co/Q8grRKnigCnHtY9D/ui-router.js:1252:54)
   at updateView (http://run.plnkr.co/Q8grRKnigCnHtY9D/ui-router.js:1306:13)
   at eventHook (http://run.plnkr.co/Q8grRKnigCnHtY9D/ui-router.js:1276:17)
   at $broadcast (http://code.angularjs.org/1.2.3/angular.js:11943:15)
   at Anonymous function (http://run.plnkr.co/Q8grRKnigCnHtY9D/ui-router.js:1067:9)
   at wrappedCallback (http://code.angularjs.org/1.2.3/angular.js:10689:15)
   at wrappedCallback (http://code.angularjs.org/1.2.3/angular.js:10689:15)

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by stas-o** [comment]
One more workaround for this issue. You can try to use ng-if="state.includes('**.new')" inside ui-view. Looks more like a hack but it works.
